### ISSUE TITLE
Trouble running package on Meteor server

### ISSUE THREAD

**Issue by micahalcorn** [revivek/oy#77]
I'm possibly missing something obvious here, but I can't seem to get this working with my Meteor application. After running `meteor npm install oy-vey`, I get the following error on the server anytime I include `import Oy from 'oy-vey';` anywhere in the server code:

```
Error: Cannot find module './components/DefaultElement'
    at makeMissingError (packages/modules-runtime.js:221:12)
    at require (packages/modules-runtime.js:231:19)
    at meteorInstall.node_modules.oy-vey.lib.Oy.js (packages/modules.js:3377:23)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at meteorInstall.server.main.js (server/main.js:1:70)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at /~/.meteor/local/build/programs/server/app/app.js:7482:1
    at /~/.meteor/local/build/programs/server/boot.js:338:34
```

I don't get that error if I import the package from the client code, but I obviously want to run it on the server so that I can render a string of html before sending an email. Any suggestions?

**Comment by micahalcorn** [comment]
Apparently, leaving off the `--save` flag during installation caused this issue. Running `meteor npm install oy-vey` seems to have fixed it.
